version: "3"
services:
  mongodb:
    image: 'mongo'
    volumes: 
      - grpc-data:/data/db
    env_file:
      - ./env/mongodb.env 

  protobuilder:
    container_name: protobuilder
    build: 
      context: ./
      dockerfile: ./dockerfiles/protobuilder
    volumes:
      - ./:/go/src/protobuilder
    stdin_open: true
    tty: true

  chit-chat-go-client:
    container_name: chit-chat-go-client
    build: 
      context: ./apps/chit-chat-go-client
      dockerfile: ../../dockerfiles/chit-chat-go-client
    volumes:
      - ./apps/chit-chat-go-client:/go/src/chit-chat-go-client
      - ccgc-extensions:/root/.vscode-server/extensions
      - ccgc-go-bin:/go/bin
    env_file:
      - ./env/chit-chat-go-client.env 
    stdin_open: true
    tty: true

  chit-chat-go:
    container_name: chit-chat-go
    build: 
      context: ./apps/chit-chat-go
      dockerfile: ../../dockerfiles/chit-chat-go
    ports:
      - 3000:3000
    volumes:
      - ./apps/chit-chat-go:/go/src/chit-chat-go
      - ccg-extensions:/root/.vscode-server/extensions
      - ccg-go-bin:/go/bin
    env_file:
      - ./env/chit-chat-go.env 
    stdin_open: true
    tty: true

volumes:
  grpc-data:
  ccg-extensions:
  ccgc-extensions:
  ccg-go-bin:
  ccgc-go-bin:
