version: "3"
services:
  mongodb:  
    image: 'mongo'
    volumes: 
      - grpc-data:/data/db
    environment: 
      MONGO_INITDB_ROOT_USERNAME: grpc
      MONGO_INITDB_ROOT_PASSWORD: grpc

  chat-server:
    container_name: chit-chat-go
    build: 
      context: ./chit-chat-go
      dockerfile: ../dockerfiles/chit-chat-go
    volumes:
      - ./chit-chat-go:/go/src/chit-chat-go
      - /root/.vscode-server/extensions
    stdin_open: true
    tty: true
volumes:
  grpc-data:
